### ISSUE TITLE
Update Level Not Working

### ISSUE THREAD

**Issue by memoblin** [foregroundprocess/BTChargeLevel#1]
Thank you in advance for sharing your code. I made some changes to the skin to display the status of various devices like mouse, keyboard, headphones, etc. However, when the battery of my mouse was exhausted, I did not see any change in the skin. Moreover, when my headphones' battery level decreases, the value in the registry does not update. I think the script is not working on my machine; it doesn't even reflect changes when run manually. But when I remove the device and reconnect it, the new value is reflected in the registry. Are you aware of this issue?

**Comment by foregroundprocess** [comment]
> Are you aware of this issue?

No, on my computer it returns the value until the battery is completely dry.

Please try running the Powershell code below (replace the device friendly name). Does it return charge level of your device?
```
$BTDeviceFriendlyName = "EDIFIER WH950NB"
$Shell = New-Object -ComObject "WScript.Shell"
$BTHDevices = Get-PnpDevice -FriendlyName "*$($BTDeviceFriendlyName)*"

if ($BTHDevices) {
    $BatteryLevels = foreach ($Device in $BTHDevices) {
        $BatteryProperty = Get-PnpDeviceProperty -InstanceId $Device.InstanceId -KeyName '{104EA319-6EE2-4701-BD47-8DDBF425BBE5} 2' |
            Where-Object { $_.Type -ne 'Empty' } |
            Select-Object -ExpandProperty Data
        Write-Host "Name: $($Device.FriendlyName) InstanceId:$($Device.InstanceId) Charge: $($BatteryProperty)"
    }
}
```
It returns Device friendly name, InstanceId and Charge level.

Then you can use the InstanceId corresponding to your device to get the key value by running another Powershell command:
```
Get-PnpDeviceProperty -InstanceId "BTHENUM\{0000111E-0000-1000-8000-00805F9B34FB}_HCIBYPASS_LOCALMFG&0002\7&3752D912&0&0CAEBDFA0677_C00000000"
```
In the output you can find the keyName '{104EA319-6EE2-4701-BD47-8DDBF425BBE5} 2' and it should contain the battery charge level.
Perhaps, in your case it is blank or the charge is written to another key. Then you will need to replace the KeyName in the Powershell script.

**Comment by memoblin** [comment]
Thanks, ForegroundProcess/BtChargeLevel. The code is working perfectly,
but I have a new question: In case my device is not connected to my
computer, how can I set the value to "NULL" or "0" so that the skin does
not appear on the desktop?

**Comment by foregroundprocess** [comment]
Check out https://github.com/foregroundprocess/BTChargeLevel/releases/tag/v1.1.0
Now you can modify the text displayed by the skin when a device is not connected.

**Comment by memoblin** [comment]
Great, this version works perfectly for my purposes.
